version: '2'
services:
    artwork-app:
        image: artwork
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://artwork-mysql:3306/artwork?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    artwork-mysql:
        extends:
            file: mysql.yml
            service: artwork-mysql
